//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.LootBoxService"/> </summary
    public sealed class LootBoxServiceClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the GetTimeLeft method on the LootBoxService microservice
        /// <see cref="Beamable.Server.LootBoxService.GetTimeLeft"/>
        /// </summary>
        public Beamable.Common.Promise<double> GetTimeLeft()
        {
            string[] serializedFields = new string[0];
            return this.Request<double>("LootBoxService", "GetTimeLeft", serializedFields);
        }
        
        /// <summary>
        /// Call the Claim method on the LootBoxService microservice
        /// <see cref="Beamable.Server.LootBoxService.Claim"/>
        /// </summary>
        public Beamable.Common.Promise<bool> Claim()
        {
            string[] serializedFields = new string[0];
            return this.Request<bool>("LootBoxService", "Claim", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersLootBoxServiceClient
    {
    }
}
